from tkinter import *
from tkinter import ttk
import mysql.connector
from tkinter import messagebox
import datetime
import re # Import regex module
import os # Import os for directory creation

# Import ReportLab modules for PDF generation
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors


class LibraryManagementSystem:
    def __init__(self, root):
        self.root = root
        self.root.title("Library Inventory Management System")
        self.root.state("zoomed") # Maximizes the window

        # ================================Variables=======================
        # Variables for Member Information
        self.member_type_var = StringVar() # Renamed for clarity
        self.prn_var = StringVar()
        self.member_id_var = StringVar() # Renamed for clarity
        self.firstname_var = StringVar()
        self.lastname_var = StringVar()
        self.address_var = StringVar() # Renamed for clarity
        self.mobile_var = StringVar()

        # Variables for Book Borrowing Information (selected from book listbox)
        self.borrow_bookid_var = StringVar() # Book ID for current borrowing record
        self.borrow_booktitle_var = StringVar()
        self.borrow_auther_var = StringVar()
        self.dateborrowed_var = StringVar()
        self.datedue_var = StringVar()
        self.daysonbook_var = StringVar()
        self.lateratefine_var = StringVar()
        self.borrow_record_id_var = StringVar() # To hold borrow_id for update/delete

        # New variables for adding books to inventory
        self.new_bookid_var = StringVar() # Will be auto-generated by DB
        self.new_booktitle_var = StringVar()
        self.new_auther_var = StringVar()
        self.new_quantity_var = StringVar()

        # Title Label
        lbltitle = Label(self.root, text="LIBRARY INVENTORY MANAGEMENT SYSTEM", bg="powder blue", fg="green", bd=10,
                         relief=RIDGE, font=("times new roman", 30, "bold"), padx=0, pady=0)
        lbltitle.pack(side=TOP, fill=X)

        # Main Frame for Data Entry and Book List
        frame = Frame(self.root, bd=12, relief=RIDGE, padx=20, bg="powder blue")
        frame.place(x=0, y=65, width=1280, height=300)

        # =================================DataFrameLeft (Member & Borrowing Info)===================================
        DataFrameLeft = LabelFrame(frame, text="Member & Borrowing Details", bg="powder blue", bd=12,
                                   relief=RIDGE, font=("times new roman", 14, "bold"), fg="green")
        DataFrameLeft.place(x=0, y=5, width=600, height=260)

        # Member Type
        lblMemebr = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Member Type", padx=0, pady=6,
                          bg="powder blue")
        lblMemebr.grid(row=0, column=0, sticky=W)

        comMember = ttk.Combobox(DataFrameLeft, textvariable=self.member_type_var, state="readonly",
                                 font=("arial", 12, "bold"), width=15)
        comMember['value'] = ("Admin Staff", "Lecturer", "Student")
        comMember.current(0)
        comMember.grid(row=0, column=1, sticky=W)

        # Member ID No. (Adjusted row after removing PRN)
        lblMemberId = Label(DataFrameLeft, font=("arial", 12, "bold"), text="ID No:", padx=2, pady=4, bg="powder blue")
        lblMemberId.grid(row=1, column=0, sticky=W) # Was row 2, now row 1
        txtMemberId = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.member_id_var, width=17)
        txtMemberId.grid(row=1, column=1, sticky=W) # Was row 2, now row 1

        # First Name (Adjusted row)
        lblFirstName = Label(DataFrameLeft, font=("arial", 12, "bold"), text="FirstName:", padx=2, pady=6,
                             bg="powder blue")
        lblFirstName.grid(row=2, column=0, sticky=W) # Was row 3, now row 2
        txtFirstName = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.firstname_var, width=17)
        txtFirstName.grid(row=2, column=1, sticky=W) # Was row 3, now row 2

        # Last Name (Adjusted row)
        lblLastName = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Surname:", padx=2, pady=6,
                            bg="powder blue")
        lblLastName.grid(row=3, column=0, sticky=W) # Was row 4, now row 3
        txtLastName = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.lastname_var, width=17)
        txtLastName.grid(row=3, column=1, sticky=W) # Was row 4, now row 3

        # Address (Adjusted row)
        lblAddress1 = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Address", padx=2, pady=6,
                            bg="powder blue")
        lblAddress1.grid(row=4, column=0, sticky=W) # Was row 5, now row 4
        txtAddress1 = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.address_var, width=17)
        txtAddress1.grid(row=4, column=1, sticky=W) # Was row 5, now row 4

        # Mobile (Adjusted row)
        lblMobile = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Mobile", padx=2, pady=6, bg="powder blue")
        lblMobile.grid(row=5, column=0, sticky=W) # Was row 6, now row 5
        txtMobile = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.mobile_var, width=17)
        txtMobile.grid(row=5, column=1, sticky=W) # Was row 6, now row 5

        # Book Title (for the borrowed book, populated from listbox selection) (Adjusted row for right column)
        lblBookTitle = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Book Title:", padx=2, pady=6,
                             bg="powder blue")
        lblBookTitle.grid(row=0, column=2, sticky=W) # Row remains 0
        txtBookTitle = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.borrow_booktitle_var, width=17, state="readonly")
        txtBookTitle.grid(row=0, column=3, sticky=W) # Row remains 0

        # Author (for the borrowed book, populated from listbox selection) (Adjusted row)
        lblAuther = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Author Name:", padx=2, pady=6,
                          bg="powder blue")
        lblAuther.grid(row=1, column=2, sticky=W) # Was row 2, now row 1
        txtAuther = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.borrow_auther_var, width=17, state="readonly")
        txtAuther.grid(row=1, column=3, sticky=W) # Was row 2, now row 1

        # Date Borrowed (Adjusted row)
        lblDateBorrowed = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Date Borrowed:", padx=2, pady=6,
                                bg="powder blue")
        lblDateBorrowed.grid(row=2, column=2, sticky=W) # Was row 3, now row 2
        txtDateBorrowed = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.dateborrowed_var,
                                width=17)
        txtDateBorrowed.grid(row=2, column=3, sticky=W) # Was row 3, now row 2

        # Date Due (Adjusted row)
        lblDateDue = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Date Due:", padx=2, pady=6,
                           bg="powder blue")
        lblDateDue.grid(row=3, column=2, sticky=W) # Was row 4, now row 3
        txtDateDue = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.datedue_var, width=17)
        txtDateDue.grid(row=3, column=3, sticky=W) # Was row 4, now row 3

        # Days on Book (Adjusted row)
        lblDaysOnBook = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Days On Book:", padx=2, pady=6,
                              bg="powder blue")
        lblDaysOnBook.grid(row=4, column=2, sticky=W) # Was row 5, now row 4
        txtDaysOnBook = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.daysonbook_var, width=17)
        txtDaysOnBook.grid(row=4, column=3, sticky=W) # Was row 5, now row 4

        # Late Return Fine (Adjusted row)
        lblLateReturnFine = Label(DataFrameLeft, font=("arial", 12, "bold"), text="Late Return Fine:", padx=2, pady=6,
                                  bg="powder blue")
        lblLateReturnFine.grid(row=5, column=2, sticky=W) # Was row 6, now row 5
        txtLateReturnFine = Entry(DataFrameLeft, font=("arial", 13, "bold"), textvariable=self.lateratefine_var,
                                  width=17)
        txtLateReturnFine.grid(row=5, column=3, sticky=W) # Was row 6, now row 5


        # ====================================Data Frame Right (Available Books)=======================================
        DataFrameRight = LabelFrame(frame, bd=12, padx=20, relief=RIDGE, bg="powder blue",
                                    font=("arial", 12, "bold"), text="Available Books")
        DataFrameRight.place(x=610, y=5, width=600, height=260)

        listScrollbar = Scrollbar(DataFrameRight)
        listScrollbar.grid(row=0, column=1, sticky="ns", pady=10)

        self.listBox = Listbox(DataFrameRight, font=("arial", 12, "bold"), width=55, height=10)
        self.listBox.bind("<<ListboxSelect>>", self.SelectBook)
        self.listBox.grid(row=0, column=0, padx=4, pady=10)
        listScrollbar.config(command=self.listBox.yview)

        self.fetch_books_to_listbox()  # Populate the listbox with books from the database

        # ================================Buttons Frame (Tabbed Interface)================================
        Framebutton = Frame(self.root, bd=12, relief=RIDGE, padx=0, bg="powder blue") # Reduced padx for notebook
        Framebutton.place(x=0, y=365, width=1280, height=100)

        self.buttons_notebook = ttk.Notebook(Framebutton)
        self.buttons_notebook.pack(fill=BOTH, expand=True, padx=5, pady=5)
        # Bind the tab change event for the action tabs notebook
        self.buttons_notebook.bind("<<NotebookTabChanged>>", self.on_action_tab_change)

        # --- Tab 1: Member Actions ---
        member_actions_tab = Frame(self.buttons_notebook, bg="powder blue")
        self.buttons_notebook.add(member_actions_tab, text="Member Actions")

        btnAddMember = Button(member_actions_tab, command=self.add_member, text="Add Member", font=("arial", 12, "bold"), width=16,
                              bg="green", fg="white")
        btnAddMember.grid(row=0, column=0, padx=5, pady=5)

        btnUpdateMember = Button(member_actions_tab, command=self.update_member, text="Update Member", font=("arial", 12, "bold"), width=16,
                                 bg="green", fg="white")
        btnUpdateMember.grid(row=0, column=1, padx=5, pady=5)

        btnDeleteMember = Button(member_actions_tab, command=self.delete_member, text="Delete Member", font=("arial", 12, "bold"), width=16,
                                 bg="green", fg="white")
        btnDeleteMember.grid(row=0, column=2, padx=5, pady=5)

        btnReset = Button(member_actions_tab, command=self.reset, text="Reset Form", font=("arial", 12, "bold"), width=16,
                          bg="purple", fg="white")
        btnReset.grid(row=0, column=4, padx=5, pady=5)

        btnExit = Button(member_actions_tab, command=self.iExit, text="Exit", font=("arial", 12, "bold"), width=16,
                         bg="red", fg="white")
        btnExit.grid(row=0, column=5, padx=5, pady=5)

        # --- Tab 2: Borrowing Actions ---
        borrowing_actions_tab = Frame(self.buttons_notebook, bg="powder blue")
        self.buttons_notebook.add(borrowing_actions_tab, text="Borrowing Actions")

        btnBorrowBook = Button(borrowing_actions_tab, command=self.borrow_book, text="Borrow Book", font=("arial", 12, "bold"), width=16,
                               bg="blue", fg="white")
        btnBorrowBook.grid(row=0, column=0, padx=5, pady=5)

        # btnUpdateBorrow = Button(borrowing_actions_tab, command=self.update_borrow_record, text="Update Borrow", font=("arial", 12, "bold"), width=16,
        #                          bg="blue", fg="white")
        # btnUpdateBorrow.grid(row=0, column=1, padx=5, pady=5) # Removed this button

        btnShowBorrowedData = Button(borrowing_actions_tab, command=self.show_borrowed_data, text="Selected Borrowed", font=("arial", 12, "bold"), width=16,
                                     bg="blue", fg="white")
        btnShowBorrowedData.grid(row=0, column=1, padx=5, pady=5) # Shifted column for this button

        btnReturnBook = Button(borrowing_actions_tab, command=self.return_book, text="Return Book", font=("arial", 12, "bold"), width=16,
                               bg="red", fg="white")
        btnReturnBook.grid(row=0, column=2, padx=5, pady=5) # Shifted column for this button

        btnReset = Button(borrowing_actions_tab, command=self.reset, text="Reset Form", font=("arial", 12, "bold"), width=16,
                          bg="purple", fg="white")
        btnReset.grid(row=0, column=3, padx=5, pady=5) # Shifted column for this button

        btnExit = Button(borrowing_actions_tab, command=self.iExit, text="Exit", font=("arial", 12, "bold"), width=16,
                         bg="red", fg="white")
        btnExit.grid(row=0, column=4, padx=5, pady=5) # Shifted column for this button

        # --- Tab 3: Book Inventory Actions ---
        book_inventory_actions_tab = Frame(self.buttons_notebook, bg="powder blue")
        self.buttons_notebook.add(book_inventory_actions_tab, text="Book Inventory Actions")

        btnAddBook = Button(book_inventory_actions_tab, command=self.add_new_book_frame, text="Add New Book", font=("arial", 12, "bold"), width=16,
                            bg="purple", fg="white")
        btnAddBook.grid(row=0, column=0, padx=5, pady=5)

        # --- General Utility Buttons (outside specific action tabs for common actions) ---
        # Moving Reset and Exit to be directly in Framebutton or consider another tab if more general buttons appear
        # For now, let's keep them on the Borrowing Actions tab for simplicity as it's the primary interaction area.
        # If you want them completely separate, we'd need another small frame for them or place them directly on Framebutton
        # but that would affect the padding/layout of the notebook.

        # btnReset = Button(borrowing_actions_tab, command=self.reset, text="Reset Form", font=("arial", 12, "bold"), width=16,
        #                   bg="blue", fg="white")
        # btnReset.grid(row=0, column=4, padx=5, pady=5) # This was a duplicate and can be removed

        # btnExit = Button(borrowing_actions_tab, command=self.iExit, text="Exit", font=("arial", 12, "bold"), width=16,
        #                  bg="blue", fg="white")
        # btnExit.grid(row=0, column=5, padx=5, pady=5) # This was a duplicate and can be removed


        # ================================Information Frames (Tabbed Interface)================================
        FrameDetails = Frame(self.root, bd=12, relief=RIDGE, padx=0, bg="powder blue") # Reduced padx for notebook
        FrameDetails.place(x=0, y=465, width=1280, height=230)

        # Create a Notebook (tabbed interface)
        self.notebook = ttk.Notebook(FrameDetails)
        self.notebook.pack(fill=BOTH, expand=True, padx=5, pady=5) # Add padding for notebook

        # --- Tab 1: Borrowed Records ---
        borrow_records_tab = Frame(self.notebook, bg="powder blue")
        self.notebook.add(borrow_records_tab, text="Borrowed Records")

        borrow_table_frame = Frame(borrow_records_tab, bd=6, relief=RIDGE, bg="powder blue")
        borrow_table_frame.pack(fill=BOTH, expand=1, padx=5, pady=5)

        xscroll_borrow = ttk.Scrollbar(borrow_table_frame, orient=HORIZONTAL)
        yscroll_borrow = ttk.Scrollbar(borrow_table_frame, orient=VERTICAL)

        # Columns for the borrowing records table
        self.library_table = ttk.Treeview(borrow_table_frame, column=(
            "borrow_id", "prn_no", "member_type", "member_id", "firstname", "lastname", "address",
            "mobile", "book_id", "book_title", "auther_name", "date_borrowed",
            "date_due", "days_on_book", "late_return_fine", "return_date", "status"
        ), xscrollcommand=xscroll_borrow.set, yscrollcommand=yscroll_borrow.set)

        xscroll_borrow.pack(side=BOTTOM, fill=X)
        yscroll_borrow.pack(side=RIGHT, fill=Y)

        xscroll_borrow.config(command=self.library_table.xview)
        yscroll_borrow.config(command=self.library_table.yview)

        # Headings for the borrowing records table
        self.library_table.heading("borrow_id", text="Borrow ID")
        self.library_table.heading("prn_no", text="PRN No.")
        self.library_table.heading("member_type", text="Member Type")
        self.library_table.heading("member_id", text="Member ID")
        self.library_table.heading("firstname", text="First Name")
        self.library_table.heading("lastname", text="Last Name")
        self.library_table.heading("address", text="Address")
        self.library_table.heading("mobile", text="Mobile")
        self.library_table.heading("book_id", text="Book ID")
        self.library_table.heading("book_title", text="Book Title")
        self.library_table.heading("auther_name", text="Author")
        self.library_table.heading("date_borrowed", text="Date Borrowed")
        self.library_table.heading("date_due", text="Date Due")
        self.library_table.heading("days_on_book", text="Days on Book")
        self.library_table.heading("late_return_fine", text="Late Fine")
        self.library_table.heading("return_date", text="Return Date")
        self.library_table.heading("status", text="Status")

        self.library_table["show"] = "headings"
        self.library_table.pack(fill=BOTH, expand=1)

        # Column widths for borrowing records
        self.library_table.column("borrow_id", width=80)
        self.library_table.column("prn_no", width=80)
        self.library_table.column("member_type", width=100)
        self.library_table.column("member_id", width=80)
        self.library_table.column("firstname", width=100)
        self.library_table.column("lastname", width=100)
        self.library_table.column("address", width=120)
        self.library_table.column("mobile", width=100)
        self.library_table.column("book_id", width=80)
        self.library_table.column("book_title", width=150)
        self.library_table.column("auther_name", width=120)
        self.library_table.column("date_borrowed", width=100)
        self.library_table.column("date_due", width=100)
        self.library_table.column("days_on_book", width=80)
        self.library_table.column("late_return_fine", width=100)
        self.library_table.column("return_date", width=100)
        self.library_table.column("status", width=80)

        # Bind the Treeview for selecting borrowing records
        self.library_table.bind("<ButtonRelease-1>", self.get_borrow_record_cursor)
        self.fetch_borrow_records() # Initial data fetch for borrowing records

        # --- Tab 2: Member Records ---
        member_records_tab = Frame(self.notebook, bg="powder blue")
        self.notebook.add(member_records_tab, text="Member Records")

        member_table_frame = Frame(member_records_tab, bd=6, relief=RIDGE, bg="powder blue")
        member_table_frame.pack(fill=BOTH, expand=1, padx=5, pady=5)

        xscroll_member = ttk.Scrollbar(member_table_frame, orient=HORIZONTAL)
        yscroll_member = ttk.Scrollbar(member_table_frame, orient=VERTICAL)

        self.member_table = ttk.Treeview(member_table_frame, column=(
            "prn_no", "member_type", "member_id", "firstname", "lastname", "address", "mobile"
        ), xscrollcommand=xscroll_member.set, yscrollcommand=yscroll_member.set)

        xscroll_member.pack(side=BOTTOM, fill=X)
        yscroll_member.pack(side=RIGHT, fill=Y)

        xscroll_member.config(command=self.member_table.xview)
        yscroll_member.config(command=self.member_table.yview)

        self.member_table.heading("prn_no", text="PRN No.")
        self.member_table.heading("member_type", text="Member Type")
        self.member_table.heading("member_id", text="Member ID")
        self.member_table.heading("firstname", text="First Name")
        self.member_table.heading("lastname", text="Last Name")
        self.member_table.heading("address", text="Address")
        self.member_table.heading("mobile", text="Mobile")

        self.member_table["show"] = "headings"
        self.member_table.pack(fill=BOTH, expand=1)

        self.member_table.column("prn_no", width=80)
        self.member_table.column("member_type", width=100)
        self.member_table.column("member_id", width=80)
        self.member_table.column("firstname", width=100)
        self.member_table.column("lastname", width=100)
        self.member_table.column("address", width=150)
        self.member_table.column("mobile", width=100)

        # Bind the Treeview for selecting member records
        self.member_table.bind("<ButtonRelease-1>", self.get_member_cursor)
        self.fetch_members() # Initial data fetch for members

        # Mysql Connection -----------

    def Connect(self):
        """Establishes a connection to the MySQL database."""
        try:
            conn = mysql.connector.connect(host="localhost", username="root", password="Almoin09", database="LibraryDBs")
            return conn
        except mysql.connector.Error as err:
            messagebox.showerror("Database Connection Error", f"Error connecting to database: {err}")
            return None

    def create_all_tables(self):
        """Creates the 'members', 'books', and 'borrower_books' tables if they don't exist."""
        conn = self.Connect()
        if conn:
            my_cursor = conn.cursor()
            try:
                # Create members table
                my_cursor.execute("""
                    CREATE TABLE IF NOT EXISTS members (
                        PRN_NO INT AUTO_INCREMENT PRIMARY KEY,
                        Member VARCHAR(255),
                        ID VARCHAR(255) UNIQUE,
                        FirstName VARCHAR(255),
                        LastNme VARCHAR(255),
                        Address1 VARCHAR(255),
                        Mobile VARCHAR(20)
                    )
                """)
                # Create books table
                my_cursor.execute("""
                    CREATE TABLE IF NOT EXISTS books (
                        book_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                        book_title VARCHAR(255) NOT NULL,
                        auther_name VARCHAR(255),
                        quantity INT NOT NULL DEFAULT 0
                    )
                """)
                # Create borrower_books table with foreign keys
                my_cursor.execute("""
                    CREATE TABLE IF NOT EXISTS borrower_books (
                        borrow_id INT AUTO_INCREMENT PRIMARY KEY,
                        prn_no INT,
                        book_id INT,
                        date_borrowed DATE,
                        date_due DATE,
                        days_on_book INT,
                        late_return_fine DECIMAL(10, 2),
                        return_date DATE NULL,
                        status VARCHAR(50) DEFAULT 'borrowed',
                        FOREIGN KEY (prn_no) REFERENCES members(PRN_NO) ON DELETE CASCADE,
                        FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE RESTRICT
                    )
                """)
                conn.commit()
                messagebox.showinfo("Database Setup", "All necessary tables (members, books, borrower_books) are ensured to exist.")
            except mysql.connector.Error as err:
                messagebox.showerror("Table Creation Error", f"Error creating tables: {err}")
            finally:
                conn.close()

    # =============================== Member Management Functions ===============================
    def add_member(self):
        """Adds a new member to the database."""
        member_type = self.member_type_var.get()
        member_id = self.member_id_var.get()
        firstname = self.firstname_var.get()
        lastname = self.lastname_var.get()
        address = self.address_var.get()
        mobile = self.mobile_var.get()

        if not member_id or not firstname or not lastname:
            messagebox.showerror("Error", "Member ID, First Name, and Last Name are required to add a member.")
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                # Check if member ID already exists
                my_cursor.execute("SELECT ID FROM members WHERE ID = %s", (member_id,))
                if my_cursor.fetchone():
                    messagebox.showerror("Error", "Member with this ID already exists.")
                    return

                my_cursor.execute("""
                    INSERT INTO members (Member, ID, FirstName, LastNme, Address1, Mobile)
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (member_type, member_id, firstname, lastname, address, mobile))
                conn.commit()

                # Get the auto-generated PRN_NO
                my_cursor.execute("SELECT LAST_INSERT_ID()")
                last_prn = my_cursor.fetchone()[0]
                self.prn_var.set(last_prn) # Internally set the PRN No.

                messagebox.showinfo("Success", f"Member '{firstname} {lastname}' added successfully with PRN: {last_prn}")
                self.fetch_members() # Refresh the member table
                self.reset() # Clear form after adding
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error adding member: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def update_member(self):
        """Updates an existing member's information in the database."""
        prn_no = self.prn_var.get()
        if not prn_no:
            messagebox.showerror("Error", "Please select a member (using PRN No.) to update.")
            return

        member_type = self.member_type_var.get()
        member_id = self.member_id_var.get()
        firstname = self.firstname_var.get()
        lastname = self.lastname_var.get()
        address = self.address_var.get()
        mobile = self.mobile_var.get()

        if not member_id or not firstname or not lastname:
            messagebox.showerror("Error", "Member ID, First Name, and Last Name cannot be empty for update.")
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                # Check for duplicate ID, excluding the current member being updated
                my_cursor.execute("SELECT ID FROM members WHERE ID = %s AND PRN_NO != %s", (member_id, prn_no))
                if my_cursor.fetchone():
                    messagebox.showerror("Error", "Another member already exists with this ID.")
                    return

                my_cursor.execute("""
                    UPDATE members SET
                        Member = %s,
                        ID = %s,
                        FirstName = %s,
                        LastNme = %s,
                        Address1 = %s,
                        Mobile = %s
                    WHERE PRN_NO = %s
                """, (member_type, member_id, firstname, lastname, address, mobile, prn_no))
                conn.commit()
                messagebox.showinfo("Success", f"Member with PRN: {prn_no} updated successfully.")
                self.fetch_members() # Refresh the member table
                self.fetch_borrow_records() # Refresh borrowed records as member details might be updated here
                self.reset() # Clear form
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error updating member: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def delete_member(self):
        """Deletes a selected member from the database."""
        prn_no = self.prn_var.get()
        if not prn_no:
            messagebox.showerror("Error", "Please select a member (using PRN No.) to delete.")
            return

        confirm = messagebox.askyesno("Confirm Deletion",
                                     f"Are you sure you want to delete member with PRN: {prn_no}?\n"
                                     "This will also delete all their borrowing records.")
        if not confirm:
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                my_cursor.execute("DELETE FROM members WHERE PRN_NO = %s", (prn_no,))
                conn.commit()
                messagebox.showinfo("Success", f"Member with PRN: {prn_no} deleted successfully.")
                self.fetch_members() # Refresh the member table
                self.fetch_borrow_records() # Refresh borrowing records (as related records might be cascade deleted)
                self.reset() # Clear form
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error deleting member: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def fetch_members(self):
        """Fetches all members and populates the member Treeview."""
        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                my_cursor.execute("SELECT PRN_NO, Member, ID, FirstName, LastNme, Address1, Mobile FROM members ORDER BY PRN_NO DESC")
                rows = my_cursor.fetchall()

                self.member_table.delete(*self.member_table.get_children())
                for i in rows:
                    self.member_table.insert("", END, values=i)
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error fetching members: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def get_member_cursor(self, event=""):
        """Populates form fields when a row in the member Treeview is selected."""
        cursor_row = self.member_table.focus()
        content = self.member_table.item(cursor_row)
        row = content['values']

        if not row: # If no row is selected or content is empty
            self.reset()
            return

        # Populate member-related variables based on the Treeview column order
        self.prn_var.set(row[0]) # PRN is not displayed but still set internally
        self.member_type_var.set(row[1])
        self.member_id_var.set(row[2])
        self.firstname_var.set(row[3])
        self.lastname_var.set(row[4])
        self.address_var.set(row[5])
        self.mobile_var.set(row[6])

        # Clear book borrowing details when a member is selected
        self.borrow_bookid_var.set("")
        self.borrow_booktitle_var.set("")
        self.borrow_auther_var.set("")
        self.dateborrowed_var.set("")
        self.datedue_var.set("")
        self.daysonbook_var.set("")
        self.lateratefine_var.set("")
        self.borrow_record_id_var.set("")
        if hasattr(self, 'txtBox') and self.txtBox.winfo_exists():
            self.txtBox.delete("1.0", END)


    # =============================== Book Borrowing Functions ===============================
    def borrow_book(self):
        """Records a book borrowing transaction."""
        prn_no = self.prn_var.get()
        book_id = self.borrow_bookid_var.get()
        member_id = self.member_id_var.get() # Ensure member ID is also filled

        if not prn_no or not book_id or not member_id:
            messagebox.showerror("Error", "Please select a member and a book to borrow.")
            return

        try:
            book_id_int = int(book_id)
        except ValueError:
            messagebox.showerror("Input Error", "Selected Book ID is not a valid number.")
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()

                # 1. Check if book is available (quantity > 0)
                my_cursor.execute("SELECT quantity FROM books WHERE book_id = %s", (book_id_int,))
                result = my_cursor.fetchone()
                if not result or result[0] <= 0:
                    messagebox.showerror("Error", "Selected book is currently out of stock.")
                    return

                # 2. Insert into borrower_books table
                date_borrowed = datetime.date.today().strftime("%Y-%m-%d")
                # Default due date 15 days from now
                date_due = (datetime.date.today() + datetime.timedelta(days=15)).strftime("%Y-%m-%d")
                days_on_book = 15 # Default days
                late_return_fine = 50.00 # Default fine

                # Populate variables for display
                self.dateborrowed_var.set(date_borrowed)
                self.datedue_var.set(date_due)
                self.daysonbook_var.set(days_on_book)
                self.lateratefine_var.set(late_return_fine)

                my_cursor.execute("""
                    INSERT INTO borrower_books (prn_no, book_id, date_borrowed, date_due, days_on_book, late_return_fine, status)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, (prn_no, book_id_int, date_borrowed, date_due, days_on_book, late_return_fine, 'borrowed'))

                # 3. Decrement book quantity in 'books' table
                my_cursor.execute("UPDATE books SET quantity = quantity - 1 WHERE book_id = %s", (book_id_int,))

                conn.commit()
                messagebox.showinfo("Success", "Book borrowed successfully!")
                self.fetch_borrow_records() # Refresh the main table
                self.fetch_books_to_listbox() # Refresh available books list
                self.reset() # Clear the input fields
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error borrowing book: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def fetch_borrow_records(self):
        """Fetches all borrowing records and populates the main Treeview."""
        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                # Join tables to get complete details for the Treeview
                my_cursor.execute("""
                    SELECT
                        bb.borrow_id,
                        m.PRN_NO,
                        m.Member,
                        m.ID,
                        m.FirstName,
                        m.LastNme,
                        m.Address1,
                        m.Mobile,
                        b.book_id,
                        b.book_title,
                        b.auther_name,
                        bb.date_borrowed,
                        bb.date_due,
                        bb.days_on_book,
                        bb.late_return_fine,
                        bb.return_date,
                        bb.status
                    FROM borrower_books bb
                    JOIN members m ON bb.prn_no = m.PRN_NO
                    JOIN books b ON bb.book_id = b.book_id
                    ORDER BY bb.borrow_id DESC
                """)
                rows = my_cursor.fetchall()

                if len(rows) != 0:
                    self.library_table.delete(*self.library_table.get_children())
                    for i in rows:
                        self.library_table.insert("", END, values=i)
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error fetching borrowing records: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    def get_borrow_record_cursor(self, event=""):
        """Populates form fields when a row in the borrowing records Treeview is selected."""
        cursor_row = self.library_table.focus()
        content = self.library_table.item(cursor_row)
        row = content['values']

        if not row: # If no row is selected or content is empty
            self.reset()
            return

        # Populate variables based on the Treeview column order
        self.borrow_record_id_var.set(row[0]) # borrow_id
        self.prn_var.set(row[1]) # prn_no
        self.member_type_var.set(row[2]) # member_type
        self.member_id_var.set(row[3]) # member_id
        self.firstname_var.set(row[4])
        self.lastname_var.set(row[5])
        self.address_var.set(row[6])
        self.mobile_var.set(row[7])
        self.borrow_bookid_var.set(row[8]) # book_id
        self.borrow_booktitle_var.set(row[9]) # book_title
        self.borrow_auther_var.set(row[10]) # auther_name
        self.dateborrowed_var.set(row[11]) # date_borrowed
        self.datedue_var.set(row[12]) # date_due
        self.daysonbook_var.set(row[13]) # days_on_book
        self.lateratefine_var.set(row[14]) # late_return_fine


    # Removed update_borrow_record function as per request
    # def update_borrow_record(self):
    #     """Updates a selected borrowing record in the database."""
    #     borrow_id = self.borrow_record_id_var.get()
    #     if not borrow_id:
    #         messagebox.showerror("Error", "Please select a borrowing record to update.")
    #         return

    #     conn = self.Connect()
    #     if conn:
    #         try:
    #             my_cursor = conn.cursor()
    #             my_cursor.execute("""
    #                 UPDATE borrower_books SET
    #                     date_borrowed = %s,
    #                     date_due = %s,
    #                     days_on_book = %s,
    #                     late_return_fine = %s
    #                 WHERE borrow_id = %s
    #             """, (
    #                 self.dateborrowed_var.get(),
    #                 self.datedue_var.get(),
    #                 self.daysonbook_var.get(),
    #                 self.lateratefine_var.get(),
    #                 borrow_id
    #             ))
    #             conn.commit()
    #             messagebox.showinfo("Success", "Borrowing record updated successfully.")
    #             self.fetch_borrow_records() # Refresh table
    #             self.reset() # Clear form
    #         except mysql.connector.Error as err:
    #             messagebox.showerror("Database Error", f"Error updating borrowing record: {err}")
    #         except Exception as e:
    #             messagebox.showerror("Error", f"An unexpected error occurred: {e}")
    #         finally:
    #             conn.close()

    def return_book(self):
        """Marks a borrowed book as returned and increments its quantity."""
        borrow_id = self.borrow_record_id_var.get()
        book_id = self.borrow_bookid_var.get()

        if not borrow_id or not book_id:
            messagebox.showerror("Error", "Please select a borrowing record to mark as returned.")
            return

        confirm = messagebox.askyesno("Confirm Return", "Are you sure you want to mark this book as returned?")
        if not confirm:
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()

                # 1. Update status and return_date in borrower_books
                return_date = datetime.date.today().strftime("%Y-%m-%d")
                my_cursor.execute("""
                    UPDATE borrower_books SET status = 'returned', return_date = %s
                    WHERE borrow_id = %s
                """, (return_date, borrow_id))

                # 2. Increment book quantity in 'books' table
                my_cursor.execute("UPDATE books SET quantity = quantity + 1 WHERE book_id = %s", (int(book_id),))

                conn.commit()
                messagebox.showinfo("Success", "Book successfully marked as returned and quantity updated.")
                self.fetch_borrow_records() # Refresh borrowing records
                self.fetch_books_to_listbox() # Refresh available books list
                self.reset() # Clear form
            except ValueError:
                messagebox.showerror("Input Error", "Book ID is not a valid number.")
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error returning book: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    # =============================== Book Inventory Management Functions ===============================
    def fetch_books_to_listbox(self):
        """Populates the available books Listbox."""
        self.listBox.delete(0, END) # Clear existing listbox entries
        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                my_cursor.execute("SELECT book_id, book_title, auther_name, quantity FROM books ORDER BY book_title ASC")
                books = my_cursor.fetchall()
                for book_id, book_title, auther_name, quantity in books:
                    self.listBox.insert(END, f"[{book_id}] {book_title} by {auther_name} (Available: {quantity})")
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error fetching books: {err}")
            finally:
                conn.close()

    def SelectBook(self, event=""):
        """Handles selection of a book from the available books Listbox."""
        selected_indices = self.listBox.curselection()
        if selected_indices:
            displayed_string = self.listBox.get(selected_indices[0])
            try:
                # Extract book_id from the format "[ID] Title by Author (Available: Quantity)"
                match = re.match(r'^\[(\d+)\]\s(.*)\sby\s(.*)\s\(Available:\s(\d+)\)$', displayed_string)
                if match:
                    selected_book_id = int(match.group(1))
                    selected_book_title = match.group(2).strip()
                    selected_auther_name = match.group(3).strip()

                    self.borrow_bookid_var.set(str(selected_book_id)) # Book ID is still set internally
                    self.borrow_booktitle_var.set(selected_book_title)
                    self.borrow_auther_var.set(selected_auther_name)

                    # Automatically set borrowing dates and fine
                    d1 = datetime.date.today()
                    d2 = datetime.timedelta(days=15)
                    d3 = d1 + d2
                    self.dateborrowed_var.set(d1.strftime("%Y-%m-%d"))
                    self.datedue_var.set(d3.strftime("%Y-%m-%d"))
                    self.daysonbook_var.set(15)
                    self.lateratefine_var.set("50.00")
                else:
                    messagebox.showerror("Error", "Could not parse selected book information.")
            except (IndexError, ValueError) as e:
                messagebox.showerror("Error", f"Invalid book selection format: {e}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred during book selection: {e}")


    def add_new_book_frame(self):
        """Opens a new window for adding a new book to the inventory."""
        self.add_book_window = Toplevel(self.root)
        self.add_book_window.title("Add New Book to Inventory")
        self.add_book_window.geometry("400x300")
        self.add_book_window.transient(self.root) # Makes the new window appear on top of the main window

        add_book_frame = LabelFrame(self.add_book_window, text="Book Information", bg="powder blue", bd=12,
                                    relief=RIDGE, font=("times new roman", 14, "bold"), fg="green")
        add_book_frame.pack(padx=20, pady=20, fill=BOTH, expand=True)

        lbl_book_title = Label(add_book_frame, font=("arial", 12, "bold"), text="Book Title:", padx=2, pady=6, bg="powder blue")
        lbl_book_title.grid(row=0, column=0, sticky=W)
        entry_book_title = Entry(add_book_frame, font=("arial", 13, "bold"), textvariable=self.new_booktitle_var, width=21)
        entry_book_title.grid(row=0, column=1, sticky=W, padx=5)

        lbl_auther_name = Label(add_book_frame, font=("arial", 12, "bold"), text="Author Name:", padx=2, pady=6, bg="powder blue")
        lbl_auther_name.grid(row=1, column=0, sticky=W)
        entry_auther_name = Entry(add_book_frame, font=("arial", 13, "bold"), textvariable=self.new_auther_var, width=21)
        entry_auther_name.grid(row=1, column=1, sticky=W, padx=5)

        lbl_quantity = Label(add_book_frame, font=("arial", 12, "bold"), text="Quantity:", padx=2, pady=6, bg="powder blue")
        lbl_quantity.grid(row=2, column=0, sticky=W)
        entry_quantity = Entry(add_book_frame, font=("arial", 13, "bold"), textvariable=self.new_quantity_var, width=21)
        entry_quantity.grid(row=2, column=1, sticky=W, padx=5)

        add_btn = Button(add_book_frame, text="Add Book to Inventory", command=self.add_book_to_db, font=("arial", 12, "bold"), bg="green", fg="white")
        add_btn.grid(row=3, column=0, columnspan=2, pady=10)

    def add_book_to_db(self):
        """Adds a new book to the 'books' inventory table."""
        book_title = self.new_booktitle_var.get()
        auther_name = self.new_auther_var.get()
        quantity = self.new_quantity_var.get()

        if not book_title or not auther_name or not quantity:
            messagebox.showerror("Error", "Book Title, Author Name, and Quantity are required fields to add a book.")
            return

        try:
            quantity = int(quantity)
            if quantity <= 0:
                messagebox.showerror("Error", "Quantity must be a positive integer.")
                return
        except ValueError:
            messagebox.showerror("Error", "Quantity must be a valid number.")
            return

        conn = self.Connect()
        if conn:
            try:
                my_cursor = conn.cursor()
                my_cursor.execute("INSERT INTO books (book_title, auther_name, quantity) VALUES (%s, %s, %s)",
                                  (book_title, auther_name, quantity))
                conn.commit()

                my_cursor.execute("SELECT LAST_INSERT_ID()")
                last_book_id = my_cursor.fetchone()[0]
                self.new_bookid_var.set(last_book_id) # Set the new book ID for display if needed

                messagebox.showinfo("Success", f"Book '{book_title}' added successfully with ID: {last_book_id}!")
                self.fetch_books_to_listbox() # Refresh the available books list
                self.add_book_window.destroy() # Close the add book window

                # Clear the new book entry fields
                self.new_booktitle_var.set("")
                self.new_auther_var.set("")
                self.new_quantity_var.set("")
            except mysql.connector.Error as err:
                messagebox.showerror("Database Error", f"Error adding book: {err}")
            except Exception as e:
                messagebox.showerror("Error", f"An unexpected error occurred: {e}")
            finally:
                conn.close()

    # =============================== Utility Functions ===============================
    def show_borrowed_data(self):
        """Displays details of the currently selected borrowing record in a text box."""
        if not self.borrow_record_id_var.get():
            messagebox.showerror("Error", "Please select a borrowing record to show details.")
            return

        if not hasattr(self, 'data_display_window') or not self.data_display_window.winfo_exists():
            self.data_display_window = Toplevel(self.root)
            self.data_display_window.title("Selected Borrowing Record Details")
            self.data_display_window.geometry("450x600")

            # Frame for text box
            text_frame = Frame(self.data_display_window)
            text_frame.pack(fill=BOTH, expand=1, padx=10, pady=10)

            self.txtBox = Text(text_frame, font=("arial", 12, "bold"), bd=5, relief=SUNKEN)
            self.txtBox.pack(fill=BOTH, expand=1)

            # Frame for buttons
            button_frame = Frame(self.data_display_window)
            button_frame.pack(pady=5)

            # Add Print Text Receipt Button (retained from previous request)
            print_text_receipt_btn = Button(button_frame, text="Print Text Receipt",
                                            command=self.print_borrow_receipt,
                                            font=("arial", 12, "bold"), bg="blue", fg="white")
            print_text_receipt_btn.pack(side=LEFT, padx=5)

            # Add Generate PDF Receipt Button (NEW)
            generate_pdf_btn = Button(button_frame, text="Generate PDF Receipt",
                                      command=self.generate_pdf_receipt,
                                      font=("arial", 12, "bold"), bg="darkgreen", fg="white")
            generate_pdf_btn.pack(side=LEFT, padx=5)

        self.txtBox.delete("1.0", END)
        self.txtBox.insert(END, "Borrow ID:\t\t" + self.borrow_record_id_var.get() + "\n")
        self.txtBox.insert(END, "PRN No:\t\t" + self.prn_var.get() + "\n")
        self.txtBox.insert(END, "Member Type:\t\t" + self.member_type_var.get() + "\n")
        self.txtBox.insert(END, "Member ID:\t\t" + self.member_id_var.get() + "\n")
        self.txtBox.insert(END, "FirstName:\t\t" + self.firstname_var.get() + "\n")
        self.txtBox.insert(END, "LastName:\t\t" + self.lastname_var.get() + "\n")
        self.txtBox.insert(END, "Address:\t\t" + self.address_var.get() + "\n")
        self.txtBox.insert(END, "Mobile No:\t\t" + self.mobile_var.get() + "\n")
        self.txtBox.insert(END, "Book ID:\t\t" + self.borrow_bookid_var.get() + "\n")
        self.txtBox.insert(END, "Book Title:\t\t" + self.borrow_booktitle_var.get() + "\n")
        self.txtBox.insert(END, "Author:\t\t" + self.borrow_auther_var.get() + "\n")
        self.txtBox.insert(END, "Date Borrowed:\t\t" + self.dateborrowed_var.get() + "\n")
        self.txtBox.insert(END, "Date Due:\t\t" + self.datedue_var.get() + "\n")
        self.txtBox.insert(END, "Days On Book:\t\t" + self.daysonbook_var.get() + "\n")
        self.txtBox.insert(END, "Late Return Fine:\t" + self.lateratefine_var.get() + "\n")

    def print_borrow_receipt(self):
        """Generates and displays a formatted text receipt for the current borrowing record."""
        receipt_content = f"""
        ========================================
             LIBRARY BOOK BORROWING RECEIPT
        ========================================

        Borrow ID:      {self.borrow_record_id_var.get()}

        --- Member Details ---
        PRN No:         {self.prn_var.get()}
        Member Type:    {self.member_type_var.get()}
        Member ID:      {self.member_id_var.get()}
        Name:           {self.firstname_var.get()} {self.lastname_var.get()}
        Address:        {self.address_var.get()}
        Mobile:         {self.mobile_var.get()}

        --- Book Details ---
        Book ID:        {self.borrow_bookid_var.get()}
        Book Title:     {self.borrow_booktitle_var.get()}
        Author:         {self.borrow_auther_var.get()}

        --- Borrowing Details ---
        Date Borrowed:  {self.dateborrowed_var.get()}
        Date Due:       {self.datedue_var.get()}
        Days on Book:   {self.daysonbook_var.get()}
        Late Return Fine: {self.lateratefine_var.get()}

        Current Date:   {datetime.date.today().strftime("%Y-%m-%d")}

        ========================================
            Thank you for using our service!
        ========================================
        """

        receipt_window = Toplevel(self.root)
        receipt_window.title("Borrowing Receipt (Text)")
        receipt_window.geometry("500x600")
        receipt_window.transient(self.data_display_window) # Keep it on top of the data display window

        receipt_text_widget = Text(receipt_window, font=("Consolas", 12), wrap=WORD)
        receipt_text_widget.pack(fill=BOTH, expand=1, padx=10, pady=10)
        receipt_text_widget.insert(END, receipt_content)
        receipt_text_widget.config(state=DISABLED) # Make text read-only

        # Optional: Add a close button for the receipt window
        close_button = Button(receipt_window, text="Close", command=receipt_window.destroy,
                              font=("arial", 12, "bold"), bg="gray", fg="white")
        close_button.pack(pady=5)

    def generate_pdf_receipt(self):
        """Generates a PDF receipt for the currently selected borrowing record."""
        borrow_id = self.borrow_record_id_var.get()
        if not borrow_id:
            messagebox.showerror("Error", "No borrowing record selected to generate PDF.")
            return

        # Define styles for PDF content
        styles = getSampleStyleSheet()
        normal_style = styles['Normal']
        heading_style = styles['h2']
        subheading_style = styles['h3']
        table_header_style = styles['h4'] # For table headers

        # Create a directory for receipts if it doesn't exist
        receipts_dir = "receipts"
        os.makedirs(receipts_dir, exist_ok=True)
        pdf_filename = os.path.join(receipts_dir, f"receipt_{borrow_id}.pdf")

        doc = SimpleDocTemplate(pdf_filename,
                                rightMargin=inch/2,
                                leftMargin=inch/2,
                                topMargin=inch/2,
                                bottomMargin=inch/2)
        Story = []

        # Title
        Story.append(Paragraph("LIBRARY BOOK BORROWING RECEIPT", styles['h1']))
        Story.append(Spacer(1, 0.2 * inch))

        # Borrow ID
        Story.append(Paragraph(f"<b>Borrow ID:</b> {borrow_id}", normal_style))
        Story.append(Spacer(1, 0.1 * inch))

        # Member Details
        Story.append(Paragraph("<b>--- Member Details ---</b>", subheading_style))
        member_data = [
            ["PRN No:", self.prn_var.get()],
            ["Member Type:", self.member_type_var.get()],
            ["Member ID:", self.member_id_var.get()],
            ["Name:", f"{self.firstname_var.get()} {self.lastname_var.get()}"],
            ["Address:", self.address_var.get()],
            ["Mobile:", self.mobile_var.get()],
        ]
        member_table = Table(member_data, colWidths=[1.5*inch, 4.5*inch])
        member_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey), # Optional: for header if there was one
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke), # Optional
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('BACKGROUND', (0,1), (-1,-1), colors.beige), # Optional: for data rows
        ]))
        Story.append(member_table)
        Story.append(Spacer(1, 0.2 * inch))

        # Book Details
        Story.append(Paragraph("<b>--- Book Details ---</b>", subheading_style))
        book_data = [
            ["Book ID:", self.borrow_bookid_var.get()],
            ["Book Title:", self.borrow_booktitle_var.get()],
            ["Author:", self.borrow_auther_var.get()],
        ]
        book_table = Table(book_data, colWidths=[1.5*inch, 4.5*inch])
        book_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('BACKGROUND', (0,0), (-1,-1), colors.lightgreen), # Optional: for data rows
        ]))
        Story.append(book_table)
        Story.append(Spacer(1, 0.2 * inch))

        # Borrowing Details
        Story.append(Paragraph("<b>--- Borrowing Details ---</b>", subheading_style))
        borrowing_data = [
            ["Date Borrowed:", self.dateborrowed_var.get()],
            ["Date Due:", self.datedue_var.get()],
            ["Days on Book:", self.daysonbook_var.get()],
            ["Late Return Fine:", self.lateratefine_var.get()],
            ["Current Date:", datetime.date.today().strftime("%Y-%m-%d")],
        ]
        borrowing_table = Table(borrowing_data, colWidths=[1.5*inch, 4.5*inch])
        borrowing_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.black),
            ('BACKGROUND', (0,0), (-1,-1), colors.lightgrey),
        ]))
        Story.append(borrowing_table)
        Story.append(Spacer(1, 0.2 * inch))

        # Footer
        Story.append(Paragraph("<i>Thank you for using our service!</i>", styles['Italic']))

        try:
            doc.build(Story)
            messagebox.showinfo("PDF Generated", f"PDF receipt saved to:\n{os.path.abspath(pdf_filename)}")
        except Exception as e:
            messagebox.showerror("PDF Generation Error", f"Failed to generate PDF: {e}")


    def reset(self):
        """Resets all input fields and closes the data display window if open."""
        self.member_type_var.set("Admin Staff") # Reset to default
        self.prn_var.set("") # PRN is not displayed but still reset
        self.member_id_var.set("")
        self.firstname_var.set("")
        self.lastname_var.set("")
        self.address_var.set("")
        self.mobile_var.set("")

        self.borrow_bookid_var.set("") # Book ID is not displayed but still reset
        self.borrow_booktitle_var.set("")
        self.borrow_auther_var.set("")
        self.dateborrowed_var.set("")
        self.datedue_var.set("")
        self.daysonbook_var.set("")
        self.lateratefine_var.set("")
        self.borrow_record_id_var.set("")

        if hasattr(self, 'txtBox') and self.txtBox.winfo_exists():
            self.txtBox.delete("1.0", END)
        self.library_table.selection_remove(self.library_table.focus()) # Deselect any row in Borrowing Treeview
        self.member_table.selection_remove(self.member_table.focus()) # Deselect any row in Member Treeview

    def iExit(self):
        """Prompts the user to confirm exit and closes the application."""
        iExit = messagebox.askyesno("Library Management System", "Do you want to exit?")
        if iExit > 0:
            self.root.destroy()
    
    def on_action_tab_change(self, event):
        """Switches the information tab based on the selected action tab."""
        selected_tab_id = self.buttons_notebook.select()
        selected_tab_text = self.buttons_notebook.tab(selected_tab_id, "text")

        if selected_tab_text == "Member Actions":
            self.notebook.select(1)  # Selects the "Member Records" tab (index 1)
        elif selected_tab_text == "Borrowing Actions":
            self.notebook.select(0)  # Selects the "Borrowed Records" tab (index 0)
        elif selected_tab_text == "Book Inventory Actions":
            # There isn't a direct "Book Inventory Records" tab,
            # so you might choose to keep it on Borrowed Records or leave as is.
            # For this example, let's keep it on Borrowed Records (index 0)
            self.notebook.select(0)
            messagebox.showinfo("Note", "Book Inventory Actions are primarily for adding new books, "
                                        "and available books are shown in the listbox above.")


if _name_ == '_main_':
    root = Tk()
    obj = LibraryManagementSystem(root)
    # Ensure all tables are created when the application starts
    obj.create_all_tables()
    root.mainloop()
